### ISSUE TITLE
Usually have to press shortcut twice to activate

### ISSUE THREAD

**Issue by billw2012** [algernon-A/LineToolLite#4] opened 2023-12-04 19:51 UTC
The first time I press it it hides the normal controls except the Theme: 
![image](https://github.com/algernon-A/LineToolLite/assets/1453936/97dd6d0b-bad3-4c52-95c0-d043c33ab5af)

The second time I press it I get the expected UI:
![image](https://github.com/algernon-A/LineToolLite/assets/1453936/f25b5395-2697-4de6-bfe8-cc2f594b92a8)

**Comment by algernon-A** [comment] 2023-12-06 05:06
Strange.  Can you reproduce and post the UI log here?

**Comment by omayhemo** [comment] 2023-12-10 18:26
I can't get the mod to work at all.  CTRL+L doesn't do anything.

**Comment by algernon-A** [comment] 2023-12-10 23:18
> I can't get the mod to work at all. CTRL+L doesn't do anything.

Did you select an object first (such as a tree)?

**Comment by omayhemo** [comment] 2023-12-11 12:09
Yep. I’ve found that I can spam the shortcut key sometimes and it’ll work on like the 4th or 5th time. But most of the time stops working all together and I cannot activate tool.

**Comment by omayhemo** [comment] 2023-12-12 12:43
Can't get it working at all now.  Shortcut spam is no longer working.

**Comment by algernon-A** [comment] 2023-12-13 07:01
Neither I nor myself have been able to reproduce this, unfortunately.

Are you using any other mods?

**Comment by algernon-A** [comment] 2024-01-25 05:21
Closing as no further response received and unable to reproduce.

**Closed by algernon-A** 2024-01-25 05:21 UTC
